name: Tag Branch on Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  tag_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tag branch
        run: |
          git tag -a pre-release -m "Tagged from pull request ${{ github.event.pull_request.number }}"
          
