name: Tag Branch
on:
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      branch_name:
        description: 'Name of the branch to tag'
        required: true
      tag_name:
        description: 'Name of the tag to create'
        required: true

jobs:
  tag_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tag branch
        run: |
          git tag -a ${{ github.event.inputs.tag_name }} -m "Tagged from branch ${{ github.event.inputs.branch_name }}"
          
